//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://SnusService", ConfigurationName="ISnusCalculator")]
public interface ISnusCalculator
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://SnusService/ISnusCalculator/CalculateNicotineAmount", ReplyAction="http://SnusService/ISnusCalculator/CalculateNicotineAmountResponse")]
    double CalculateNicotineAmount(double antalDosor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://SnusService/ISnusCalculator/CalculateNicotineAmount", ReplyAction="http://SnusService/ISnusCalculator/CalculateNicotineAmountResponse")]
    System.Threading.Tasks.Task<double> CalculateNicotineAmountAsync(double antalDosor);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISnusCalculatorChannel : ISnusCalculator, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SnusCalculatorClient : System.ServiceModel.ClientBase<ISnusCalculator>, ISnusCalculator
{
    
    public SnusCalculatorClient()
    {
    }
    
    public SnusCalculatorClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SnusCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SnusCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SnusCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public double CalculateNicotineAmount(double antalDosor)
    {
        return base.Channel.CalculateNicotineAmount(antalDosor);
    }
    
    public System.Threading.Tasks.Task<double> CalculateNicotineAmountAsync(double antalDosor)
    {
        return base.Channel.CalculateNicotineAmountAsync(antalDosor);
    }
}
